#!/bin/bash
#
# check that the program ls is found in the current working directory
# where /bin doesn't exist in path and cwd is called at the end of path

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:/usr/local/games:"
# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
return=`$CAT "$OUTPUTFILE"`
if [ "$return" == "cisfun" ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file
