#!/bin/bash
#
# test cd by changing to /bin directory
command="cd /bin
pwd"
bin_test="checker_bin_test_$RANDOM"

# clean up
stop_shell
rm -f $bin_test

# create a pseudo random file
touch $bin_test

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "/bin"`
if [ $nmatch -eq 1 ]; then
 print_ok
else
 print_ko
fi

# clean up
stop_shell
rm -f $bin_test
